= Warsztaty z wielowątkowości w Jawie - CountDownLatch

////
TODO: Ustalić w jaki sposób poruszać się po warsztacie i uwzględnić to w README
    Sugestia - naszym zdaniem gałąź master powinna zawierać jedynie wprowadzenie i jedno przykładowe zadanie (B_przykład),
    a reszta powinna zawierać szkielety klas i polecenia. Druga gałąź "rozwiązania" będzie miała dostępne zrobione przez nas
    propozycje rozwiązań. Dzięki temu osoba przechodząca warsztat będzie mogła wygodnie i łatwo poruszać się między zadaniami
    i przykładami rozwiązań.
////

Hejo! Zapraszam na warsztacik z CountDownLatch!

Warsztat powinien zająć między 120-150 minut.

Warsztat możesz rozwiązać na dwa sposoby. Poruszając się po pakietach w porządku alfabetycznym,
lub przełączać się między poszczególnymi gałęziami. Polecam sposób z gałęziami, ponieważ nie będzie
Cię kusiło podglądanie rozwiązań z przykładów.

W przypadku rozwiązywania na masterze:
Poruszaj się po pakietach w porządku alfabetycznym, czytaj treść, zrozum koncept,
a następnie spróbuj się z zadaniami!

W razie problemów, kombinuj chwilę sam, poczytaj dokumentację, przemyśl rozwiązanie.

Jesteśmy świadomy tego, że przykłady pewnie nie są idealne. Staraliśmy się, żeby były stosunkowo proste i obrazowały koncept.

Jeżeli się spodoba, zachęcamy do odznaczek ;D jeżeli się nie podobało, piszcie śmiało co możemy zrobić lepiej następnym razem.

Powodzonka!

Kacper Staszek, Marcin Ogorzałek